import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
// import styles from "../styles/Home.module.css";
import { useEffect, useMemo, useState } from "react";

// import thirdweb
import { useWeb3 } from "@3rdweb/hooks";
import { WalletConnectButton } from "../src/components/WalletConnectButton";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Fanclub</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-black h-screen flex flex-col items-center justify-center">
        <div className="relative w-96 h-96">
          <Image
            src="/cyberconnect-white.png"
            layout="fill"
            objectFit="contain"
          />
        </div>
        <div className="flex flex-col items-center justify-center relative">
          <h1 className="text-white text-5xl pb-16 font-bold">Fan Club</h1>
          <div className="text-white mb-4">
            Welcome to Cyber Connect FanClub. This is a demo where you can claim
            a membership NFT as long as you follow us.
          </div>
          <WalletConnectButton />
          <h1 className="text-white m-5">
            Please connect to Ehterum Rinkkeby Testnet.
          </h1>
        </div>
      </div>
    </div>
  );
};

export default Home;
